// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shabakat.Infrastructure.Persistence;

#nullable disable

namespace Shabakat.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260813164809_add_auditentity_type_enum")]
    partial class add_auditentity_type_enum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Shabakat.Domain.Entities.AmpereSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CommercialPricePerAmp")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HoursPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("IndustrialPricePerAmp")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerAmp")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ResidentialPricePerAmp")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HoursPerDay")
                        .IsUnique();

                    b.ToTable("AmpereSchedules");
                });

            modelBuilder.Entity("Shabakat.Domain.Entities.AppPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AmpereProrateByDaysEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AmpereSchedulePricingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CommercialFixedCharge")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CommercialPricePerAmp")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CommercialPricePerKilowat")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CommercialTVA")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DueDate")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FixedCharge")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("IndustrialFixedCharge")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("IndustrialPricePerAmp")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("IndustrialPricePerKilowat")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("IndustrialTVA")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerAmp")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PricePerKilowat")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ResidentialFixedCharge")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ResidentialPricePerAmp")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ResidentialPricePerKilowat")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ResidentialTVA")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TVA")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TriggerDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggerMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppPreferences");
                });

            modelBuilder.Entity("Shabakat.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Shabakat.Domain.Entities.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Shabakat.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Action", "CreatedAt");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Shabakat.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AmpereScheduleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BoxId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Building")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CableName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerRelation")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<byte>("CustomerStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FixedChargeOverride")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Floor")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PlanValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PriceOverride")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateOnly>("SubscriptionDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TVAOverride")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AmpereScheduleId");

                    b.HasIndex("AreaId");

                    b.HasIndex("BoxId");

                    b.HasIndex("Name");

                    b.HasIndex("Phone");

                    b.ToTable("Customers", t =>
                        {
                            t.HasCheckConstraint("CK_Customers_PricingOverrides_AllOrNothing", "(\r\n    \"PriceOverride\" IS NULL AND \"FixedChargeOverride\" IS NULL AND \"TVAOverride\" IS NULL\r\n)\r\nOR\r\n(\r\n    \"PriceOverride\" IS NOT NULL AND \"FixedChargeOverride\" IS NOT NULL AND \"TVAOverride\" IS NOT NULL\r\n)");
                        });
                });

            modelBuilder.Entity("Shabakat.Domain.Entities.DistributionBox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationNote")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Name");

                    b.ToTable("DistributionBoxes");
                });

            modelBuilder.Entity("Shabakat.Domain.Entities.Expenses", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpenseType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseDate");

                    b.ToTable("Expenses", t =>
                        {
                            t.HasCheckConstraint("CK_Expenses_Amount", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("Shabakat.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountDue")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,4)")
                        .HasComputedColumnSql("\"TotalAmount\" - \"PaidAmount\"", true);

                    b.Property<decimal?>("BilledConsumption")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FixedCharge")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("InvoiceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvoiceStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TVA")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Invoices_InvoiceNumber");

                    b.ToTable("Invoices", t =>
                        {
                            t.HasCheckConstraint("CK_Invoices_PaidAmount", "\"PaidAmount\" >= 0 AND \"PaidAmount\" <= \"TotalAmount\"");
                        });
                });

            modelBuilder.Entity("Shabakat.Domain.Entities.InvoiceSkip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BillingPeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BillingPeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "BillingPeriodStart", "BillingPeriodEnd")
                        .IsUnique()
                        .HasDatabaseName("UQ_InvoiceSkips_Customer_Period");

                    b.ToTable("InvoiceSkips");
                });

            modelBuilder.Entity("Shabakat.Domain.Entities.MeterReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInitial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("PeriodYearMonth")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasComputedColumnSql("(CAST(strftime('%Y', \"ReadingDate\") AS INTEGER) * 100 + CAST(strftime('%m', \"ReadingDate\") AS INTEGER))", true);

                    b.Property<DateOnly>("ReadingDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReadingValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("UQ_MeterReadings_CustomerId_IsInitial")
                        .HasFilter("\"IsInitial\" = 1");

                    b.HasIndex("CustomerId", "PeriodYearMonth")
                        .IsUnique()
                        .HasDatabaseName("UQ_MeterReadings_CustomerId_PeriodYearMonth")
                        .HasFilter("\"IsInitial\" = 0");

                    b.ToTable("MeterReadings");
                });

            modelBuilder.Entity("Shabakat.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Amount", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("Shabakat.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Shabakat.Domain.Entities.AmpereSchedule", "AmpereSchedule")
                        .WithMany("Customers")
                        .HasForeignKey("AmpereScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Shabakat.Domain.Entities.Area", "Area")
                        .WithMany("Customers")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Shabakat.Domain.Entities.DistributionBox", "DistributionBox")
                        .WithMany("Customers")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AmpereSchedule");

                    b.Navigation("Area");

                    b.Navigation("DistributionBox");
                });

            modelBuilder.Entity("Shabakat.Domain.Entities.DistributionBox", b =>
                {
                    b.HasOne("Shabakat.Domain.Entities.Area", "Area")
                        .WithMany("DistributionBoxes")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Shabakat.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("Shabakat.Domain.Entities.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Shabakat.Domain.Entities.InvoiceSkip", b =>
                {
                    b.HasOne("Shabakat.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Shabakat.Domain.Entities.MeterReading", b =>
                {
                    b.HasOne("Shabakat.Domain.Entities.Customer", "Customer")
                        .WithMany("MeterReadings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Shabakat.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Shabakat.Domain.Entities.Customer", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shabakat.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Shabakat.Domain.Entities.AmpereSchedule", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Shabakat.Domain.Entities.Area", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("DistributionBoxes");
                });

            modelBuilder.Entity("Shabakat.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("MeterReadings");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Shabakat.Domain.Entities.DistributionBox", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Shabakat.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
