namespace Shabakat.Application.DTOs.Preferences;

public sealed record GetPreferencesResponse(
    decimal PricePerKilowat,
    decimal PricePerAmp,
    decimal FixedCharge,
    decimal TVA,
    decimal ResidentialPricePerAmp,
    decimal ResidentialPricePerKilowat,
    decimal ResidentialFixedCharge,
    decimal ResidentialTVA,
    decimal CommercialPricePerAmp,
    decimal CommercialPricePerKilowat,
    decimal CommercialFixedCharge,
    decimal CommercialTVA,
    decimal IndustrialPricePerAmp,
    decimal IndustrialPricePerKilowat,
    decimal IndustrialFixedCharge,
    decimal IndustrialTVA,
    string Language,
    int DueDate,
    bool AmpereSchedulePricingEnabled,
    bool AmpereProrateByDaysEnabled);

public sealed record UpdatePreferencesRequest(
    decimal PricePerKilowat,
    decimal PricePerAmp,
    decimal FixedCharge,
    decimal TVA,
    decimal ResidentialPricePerAmp,
    decimal ResidentialPricePerKilowat,
    decimal ResidentialFixedCharge,
    decimal ResidentialTVA,
    decimal CommercialPricePerAmp,
    decimal CommercialPricePerKilowat,
    decimal CommercialFixedCharge,
    decimal CommercialTVA,
    decimal IndustrialPricePerAmp,
    decimal IndustrialPricePerKilowat,
    decimal IndustrialFixedCharge,
    decimal IndustrialTVA,
    string Language,
    int DueDate,
    bool AmpereSchedulePricingEnabled,
    bool AmpereProrateByDaysEnabled);
